name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest]

steps:
  -
    name: Checkout code
    uses: actions/checkout@v2
  -
    name: Serve Files
    uses: Eun/http-server-action@v1
    with:
      directory: ${{ github.workspace }}
      port: 8080
      no-cache: false
      index-files: |
        ["index.html"]
      allowed-methods: |
        ["GET", "HEAD"]
  -
    run: http-server
