name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - run: echo ${{ github.workspace }}
      - name: Install http
        run: npm install -g http-server
        path: ${{ github.workspace }}
      - name: NPM Install
        run: npm start > /dev/null &
        path: ${{ github.workspace }}
      - name: Test
        run: curl localhost:8080/index.html
        path: ${{ github.workspace }}
